### ISSUE TITLE
Date format seems weird

### ISSUE THREAD

**Issue by rikusen0335** [Littlegolden/flarum-lang-japanese#6]
![screenshot_2020-09-25_03-18-04-MinecraftForumJPおよび他19ページ-個人-Microsoft​Edge](https://user-images.githubusercontent.com/19174234/94183780-eca9cd00-fedd-11ea-9ef0-65874d4017b7.png)

I found that the Japanese date format seems unnatural.
This should be like: `8月22日に投稿されました`

I wanna PR commits, but I actually couldn't figure out why this happens.

**Comment by littlegolden** [comment]
This is due to the fact that the Flarum isn't using the common time format `ll`.

Instead, Flarum use
```
e.format("D MMM"):e.format("MMM 'YY")
```
&
```
moment(u).format("MMMM YYYY")
```
in `/vendor/flarum/core/js/dist/forum.js`

So, you can change these format into `ll` by editing the file, after that, clear the cache, this will be the easy way. Or, create an extension to solve that.

**Comment by rikusen0335** [comment]
Ohhh... okay, I understood. Thanks.

**Comment by rikusen0335** [comment]
Oh but, btw, why [config.js](https://github.com/Littlegolden/flarum-lang-japanese/blob/master/locale/config.js) isn't working?

**Comment by littlegolden** [comment]
Do you mean 令和 part? Other part works fine. I'm sorry, I didn't find any information about how to display Reign Title in the Chinese Internet.
![image](https://user-images.githubusercontent.com/35162802/94259034-6aaeb800-ff60-11ea-8953-ec155c8bf5d3.png)

**Comment by rikusen0335** [comment]
Ah no, just, I mean there is a line called `longDateFormat:`, but yes, it's just a format. Never mind.

**Comment by littlegolden** [comment]
`longDateFormat` well they work under my practice. They did't work on your side? Maybe something is wrong.

**Comment by rikusen0335** [comment]
Hmm, I'm confusing. Could you lemme see that working?

**Comment by littlegolden** [comment]
Sorry for the delay
https://drive.google.com/file/d/1ZmaT4zE9ZmhMmmPUB2RvWuhJWKGXkiVH/view?usp=sharing

**Comment by rikusen0335** [comment]
No problem about delaying. Thank you.
